### ISSUE TITLE
This can be a `const`

### ISSUE THREAD

**Issue by jamesjacko** [swgj19/ToDoList#9]
https://github.com/swgj19/ToDoList/blob/7aa484bbe7eebd277da5874fb48c88ab48ddc12f/js/app.js#L8

In Js and other languages a variable which references an array is just a reference to a spot in memory so 

``` js
const arr = [];
arr.push("hello");
```
is fine, however
```js
const arr = [];
arr = []; // ncaught TypeError: Assignment to constant variable.
```
here you are trying to assign a new array to the constant variable

So the above line should be changed to 

```js
const todos = [];
```

As you want the reference in memory to remain constant.

**Comment by swgj19** [comment]
That is a great explanation of how it works. Changed it. thanks

**Comment by swgj19** [comment]
After I changed let todos = []; to a const variable the local storage stopped working for some reason.

**Comment by jamesjacko** [comment]
Ok so the line 126 sets `todos` to a new array `todos = JSON.parse(reference);` which is where the error comes in. You can get around this by emptying the array then filling it with the result of the `JSON.parse()` but I think this is unnecessary. But definitely something worth knowing.

```js
// remove all elements from the array using splice from 0 to length - 1
todos.splice(0, todos.length);
// push the contents of the localStorage JSON using the spread operator
todos.push(...JSON.parse(reference);
```

**Comment by swgj19** [comment]
That is good to know. Thank you.
